<?php
namespace App\Models\Response;

enum OAuthCode: string {
  case MISSING_CODE_OR_STATE = "MISSING_CODE_OR_STATE";
  case INVALID_CODE = "INVALID_CODE";
  case INVALID_STATE = "INVALID_STATE";
  case INVALID_REDIRECT_URI = "INVALID_REDIRECT_URI";
  case INVALID_CLIENT_ID = "INVALID_CLIENT_ID";
  case INVALID_CLIENT_SECRET = "INVALID_CLIENT_SECRET";
  case INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN";
  case EXPIRED_ACCESS_TOKEN = "EXPIRED_ACCESS_TOKEN";
  case REVOKED_ACCESS_TOKEN = "REVOKED_ACCESS_TOKEN";
  case INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE";
}

enum AuthCode: string {
  case INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
  case ACCOUNT_LOCKED = "ACCOUNT_LOCKED";
  case ACCOUNT_DISABLED = "ACCOUNT_DISABLED";
  case MISSING_CODE_OR_STATE = "MISSING_CODE_OR_STATE";
}


enum Code: string {
  // OAuth Codes
  case INVALID_CODE = "INVALID_CODE";
  case INVALID_STATE = "INVALID_STATE";
  case INVALID_REDIRECT_URI = "INVALID_REDIRECT_URI";
  case INVALID_CLIENT_ID = "INVALID_CLIENT_ID";
  case INVALID_CLIENT_SECRET = "INVALID_CLIENT_SECRET";
  case INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN";
  case EXPIRED_ACCESS_TOKEN = "EXPIRED_ACCESS_TOKEN";
  case REVOKED_ACCESS_TOKEN = "REVOKED_ACCESS_TOKEN";
  case INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE";
  case MISSING_CODE_OR_STATE = "MISSING_CODE_OR_STATE";
  case TOKEN_EXCHANGE_FAILED = "TOKEN_EXCHANGE_FAILED";


  // Auth Codes
  case INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
  case ACCOUNT_LOCKED = "ACCOUNT_LOCKED";
  case ACCOUNT_DISABLED = "ACCOUNT_DISABLED";
  case UNAUTHORIZED = "UNAUTHORIZED";
  case SESSION_NOT_FOUND = "SESSION_NOT_FOUND";

  // Permission Codes
  case PERMISSION_DENIED = "PERMISSION_DENIED";
  case UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS";

  // General Codes
  case INVALID_INPUT = "INVALID_INPUT";
  case RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
  case SERVER_ERROR = "SERVER_ERROR";
  case SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";

  // Validation Codes
  case VALIDATION_FAILED = "VALIDATION_FAILED";
  case MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS";
  case INVALID_FIELD_FORMAT = "INVALID_FIELD_FORMAT";
  case FIELD_TOO_LONG = "FIELD_TOO_LONG";
  case FIELD_TOO_SHORT = "FIELD_TOO_SHORT";
  case FIELD_NOT_UNIQUE = "FIELD_NOT_UNIQUE";

  // Database Codes
  case DATABASE_ERROR = "DATABASE_ERROR";
  case RECORD_NOT_FOUND = "RECORD_NOT_FOUND";
  case DUPLICATE_RECORD = "DUPLICATE_RECORD";
  case FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION";

  // API Codes
  case RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
  case API_VERSION_NOT_SUPPORTED = "API_VERSION_NOT_SUPPORTED";
  case ENDPOINT_NOT_FOUND = "ENDPOINT_NOT_FOUND";
  case METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED";
  case AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
  case TOKEN_EXPIRED = "TOKEN_EXPIRED";
  case TOKEN_INVALID = "TOKEN_INVALID";
  case TOKEN_MISSING = "TOKEN_MISSING";
  case TOKEN_REVOKED = "TOKEN_REVOKED";
}
